[2020-12-14 12:03:12] request.INFO: Matched route "site_partners". {"route":"site_partners","route_parameters":{"_route":"site_partners","_controller":"App\\Controller\\SiteController::partner"},"request_uri":"https://127.0.0.1:8000/partenaires","method":"GET"} []
[2020-12-14 12:03:12] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-12-14 12:03:12] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-14 12:03:12] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-14 12:03:12] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.status AS status_4, t0.logo AS logo_5, t0.url AS url_6 FROM partner t0 WHERE t0.status = ?' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist" at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 42 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.status AS status_4, t0.logo AS logo_5, t0.url AS url_6 FROM partner t0 WHERE t0.status = ?' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:42, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)"} []
[2020-12-14 12:03:12] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-12-14 12:03:32] request.INFO: Matched route "partner_index". {"route":"partner_index","route_parameters":{"_route":"partner_index","_controller":"App\\Controller\\Admin\\PartnerController::index"},"request_uri":"https://127.0.0.1:8000/admin/partenaire/","method":"GET"} []
[2020-12-14 12:03:32] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-12-14 12:03:32] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-14 12:03:32] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-14 12:03:32] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2020-12-14 12:03:32] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"Admin"} []
[2020-12-14 12:03:32] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.status AS status_4, t0.logo AS logo_5, t0.url AS url_6 FROM partner t0':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist" at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 42 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.status AS status_4, t0.logo AS logo_5, t0.url AS url_6 FROM partner t0':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:42, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:83, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78)"} []
[2020-12-14 12:03:32] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2020-12-14 12:03:41] request.INFO: Matched route "partner_index". {"route":"partner_index","route_parameters":{"_route":"partner_index","_controller":"App\\Controller\\Admin\\PartnerController::index"},"request_uri":"https://127.0.0.1:8000/admin/partenaire/","method":"GET"} []
[2020-12-14 12:03:41] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-12-14 12:03:41] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-14 12:03:41] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-14 12:03:41] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2020-12-14 12:03:42] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"Admin"} []
[2020-12-14 12:03:42] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.status AS status_4, t0.logo AS logo_5, t0.url AS url_6 FROM partner t0':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist" at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 42 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.status AS status_4, t0.logo AS logo_5, t0.url AS url_6 FROM partner t0':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:42, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:83, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78)"} []
[2020-12-14 12:03:42] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2020-12-14 12:04:14] request.INFO: Matched route "site_partners". {"route":"site_partners","route_parameters":{"_route":"site_partners","_controller":"App\\Controller\\SiteController::partner"},"request_uri":"https://127.0.0.1:8000/partenaires","method":"GET"} []
[2020-12-14 12:04:14] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-12-14 12:04:14] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-14 12:04:14] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-14 12:04:14] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.status AS status_4, t0.logo AS logo_5, t0.url AS url_6 FROM partner t0 WHERE t0.status = ?' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist" at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 42 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.status AS status_4, t0.logo AS logo_5, t0.url AS url_6 FROM partner t0 WHERE t0.status = ?' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:42, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'exam-symfony.partner' doesn't exist at /Users/arnaudbassey/Documents/Ecole/DWWM/Initiation symphony/dwm-blog-exam/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)"} []
[2020-12-14 12:04:14] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2020-12-14 12:04:14] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"Admin"} []
[2020-12-14 12:04:14] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2020-12-17 16:21:42] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://127.0.0.1:8000/connexion","method":"POST"} []
[2020-12-17 16:21:42] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-12-17 16:21:42] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:21:42] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:21:42] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:21:42] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.username AS username_5, t0.register_at AS register_at_6 FROM user t0 WHERE t0.email = ? LIMIT 1' with params ["arnaud.bassey@next-u.fr"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list'" at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.username AS username_5, t0.register_at AS register_at_6 FROM user t0 WHERE t0.email = ? LIMIT 1' with params [\"arnaud.bassey@next-u.fr\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)"} []
[2020-12-17 16:21:51] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://127.0.0.1:8000/connexion","method":"POST"} []
[2020-12-17 16:21:51] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-12-17 16:21:51] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:21:51] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:21:51] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:21:51] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.username AS username_5, t0.register_at AS register_at_6 FROM user t0 WHERE t0.email = ? LIMIT 1' with params ["arnaud.bassey@next-u.fr"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list'" at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.username AS username_5, t0.register_at AS register_at_6 FROM user t0 WHERE t0.email = ? LIMIT 1' with params [\"arnaud.bassey@next-u.fr\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)"} []
[2020-12-17 16:22:26] console.ERROR: Error thrown while running command "'make:migration'". Message: "There are no commands defined in the "make" namespace.  You may be looking for a command provided by the "MakerBundle" which is currently not installed. Try running "composer require symfony/maker-bundle --dev"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\". at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/symfony/framework-bundle/EventListener/SuggestMissingPackageSubscriber.php:74)","command":"'make:migration'","message":"There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\"."} []
[2020-12-17 16:23:19] console.ERROR: Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred while executing 'CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, published_at DATETIME NOT NULL, is_active TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'article' already exists" {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableExistsException(code: 0): An exception occurred while executing 'CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, published_at DATETIME NOT NULL, is_active TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'article' already exists at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:38, Doctrine\\DBAL\\Driver\\PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'article' already exists at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:83, PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'article' already exists at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78)","command":"doctrine:migrations:migrate","message":"An exception occurred while executing 'CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, published_at DATETIME NOT NULL, is_active TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'article' already exists"} []
[2020-12-17 16:23:19] console.DEBUG: Command "doctrine:migrations:migrate" exited with code "1" {"command":"doctrine:migrations:migrate","code":1} []
[2020-12-17 16:23:32] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://127.0.0.1:8000/connexion","method":"POST"} []
[2020-12-17 16:23:32] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-12-17 16:23:32] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:23:32] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:23:32] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:23:32] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.username AS username_5, t0.register_at AS register_at_6 FROM user t0 WHERE t0.email = ? LIMIT 1' with params ["arnaud.bassey@next-u.fr"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list'" at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.username AS username_5, t0.register_at AS register_at_6 FROM user t0 WHERE t0.email = ? LIMIT 1' with params [\"arnaud.bassey@next-u.fr\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)"} []
[2020-12-17 16:33:36] request.INFO: Matched route "site_index". {"route":"site_index","route_parameters":{"_route":"site_index","_controller":"App\\Controller\\SiteController::index"},"request_uri":"https://127.0.0.1:8000/","method":"GET"} []
[2020-12-17 16:33:36] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-12-17 16:33:36] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:33:36] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:33:36] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2020-12-17 16:33:36] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.username AS username_5, t0.register_at AS register_at_6 FROM user t0 WHERE t0.id = ?' with params [14]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list'")." at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/Tp-Symfony/ArnaudBassey-blog/templates/site/layout.html.twig line 32 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.username AS username_5, t0.register_at AS register_at_6 FROM user t0 WHERE t0.id = ?' with params [14]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list'\"). at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/Tp-Symfony/ArnaudBassey-blog/templates/site/layout.html.twig:32, Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.username AS username_5, t0.register_at AS register_at_6 FROM user t0 WHERE t0.id = ?' with params [14]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)"} []
[2020-12-17 16:33:39] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://127.0.0.1:8000/connexion","method":"POST"} []
[2020-12-17 16:33:39] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-12-17 16:33:39] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:33:39] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:33:39] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-17 16:33:39] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.username AS username_5, t0.register_at AS register_at_6 FROM user t0 WHERE t0.email = ? LIMIT 1' with params ["arnaud.bassey@next-u.fr"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list'" at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.username AS username_5, t0.register_at AS register_at_6 FROM user t0 WHERE t0.email = ? LIMIT 1' with params [\"arnaud.bassey@next-u.fr\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.password' in 'field list' at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)"} []
[2020-12-18 16:07:59] request.INFO: Matched route "site_partners". {"route":"site_partners","route_parameters":{"_route":"site_partners","_controller":"App\\Controller\\SiteController::partner"},"request_uri":"https://localhost:8000/partenaires","method":"GET"} []
[2020-12-18 16:07:59] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-12-18 16:07:59] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-18 16:07:59] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-18 16:07:59] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/partenaires" is not callable: Expected method "partner" on class "App\Controller\SiteController". Available methods: "index", "about", "contact", "blog", "showArticle", "showCategory", "blogSidebar", "setContainer", "getSubscribedServices"." at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 88 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/partenaires\" is not callable: Expected method \"partner\" on class \"App\\Controller\\SiteController\". Available methods: \"index\", \"about\", \"contact\", \"blog\", \"showArticle\", \"showCategory\", \"blogSidebar\", \"setContainer\", \"getSubscribedServices\". at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/symfony/http-kernel/Controller/ControllerResolver.php:88, InvalidArgumentException(code: 0): Expected method \"partner\" on class \"App\\Controller\\SiteController\". Available methods: \"index\", \"about\", \"contact\", \"blog\", \"showArticle\", \"showCategory\", \"blogSidebar\", \"setContainer\", \"getSubscribedServices\". at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/symfony/http-kernel/Controller/ControllerResolver.php:136)"} []
[2020-12-18 16:07:59] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2020-12-18 16:07:59] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"Arnaudadmin"} []
[2020-12-18 16:07:59] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2020-12-20 14:47:08] request.INFO: Matched route "site_partners". {"route":"site_partners","route_parameters":{"_route":"site_partners","_controller":"App\\Controller\\SiteController::partner"},"request_uri":"https://localhost:8000/partenaires","method":"GET"} []
[2020-12-20 14:47:08] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-12-20 14:47:08] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-20 14:47:08] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\AppAuthenticator"} []
[2020-12-20 14:47:08] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/partenaires" is not callable: Expected method "partner" on class "App\Controller\SiteController". Available methods: "index", "about", "contact", "blog", "showArticle", "showCategory", "blogSidebar", "setContainer", "getSubscribedServices"." at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 88 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/partenaires\" is not callable: Expected method \"partner\" on class \"App\\Controller\\SiteController\". Available methods: \"index\", \"about\", \"contact\", \"blog\", \"showArticle\", \"showCategory\", \"blogSidebar\", \"setContainer\", \"getSubscribedServices\". at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/symfony/http-kernel/Controller/ControllerResolver.php:88, InvalidArgumentException(code: 0): Expected method \"partner\" on class \"App\\Controller\\SiteController\". Available methods: \"index\", \"about\", \"contact\", \"blog\", \"showArticle\", \"showCategory\", \"blogSidebar\", \"setContainer\", \"getSubscribedServices\". at /Users/arnaudbassey/Documents/Ecole/WebTech/PHP-Symfony/webtech-php-code/ArnaudBassey-blog/vendor/symfony/http-kernel/Controller/ControllerResolver.php:136)"} []
[2020-12-20 14:47:08] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2020-12-20 14:47:08] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"Arnaudadmin"} []
[2020-12-20 14:47:08] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
